name: mobx_tut
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  flutter_hooks: ^0.18.6
  cloud_firestore: ^4.8.2
  image_picker: ^1.0.0
  firebase_storage: ^11.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0

flutter:
  uses-material-design: true


